Setup angular
hopeaisulu/inkubasia-hr-tutorial pull request #3
Opened 2023-10-19 17:22 UTC by hopeaisulu

2023-10-21 16:27 UTC, networkflow requested changes
Nice work, this is a slightly tricky commit but you figured it out!

It's almost all good, but requesting changes for a little more detail in your summary. Instead of pretending that you're writing a summary for me to review (since I created the assignment and know all the context), pretend you're writing a summary for someone else to review who doesn't know all the context about what your plan is to build the app:
* You installed a new npm package `@nestjs/serve-static`, but you didn't mention that you installed it, or explain why you installed it
* Instead of "Set up NestJS to run Angular app", I would be more specific: something like explaining you configured NestJS to serve all web requests from the static-files directory `/client/dist/client`, which contains the compiled Angular HTML/JS/CSS files. (It's ok if you don't 100% understand what's going on, but I would try to explain what this change is doing as specifically as you can! Sometimes writing a commit message makes you realize you don't understand something as well as you thought, and it can be a good opportunity to learn 😄)
* I would probably be a little more specific about what effect this commit has on the app: basically instead of returning "Hello Aisulu", it now renders a fancy home page created by Angular. It doesn't have to be long, but maybe just in the test plan instead of saying "See Angular app", you could say "The app now renders the default homepage created by the Angular framework".

2023-10-21 16:27 UTC, networkflow commented on .dockerignore
> +Thumbs.db
These files are all in the `client/` directory: you need to add `client/` to them all (be careful about lines that start with `!`, which are exceptions (files that should NOT be ignored): you need to keep the `!` at the beginning of the line)

It might also be good to add a heading comment like `### Files to ignore in client/ ###` to mark off the section with client files in `.dockerignore`

2023-10-21 16:27 UTC, networkflow commented on server/learnings.txt
> +* Run test for NestJS: `ng test`
nit: I think you meant `Run tests for Angular` :)

2023-10-21 16:27 UTC, networkflow commented on Dockerfile
>  COPY . .
nit: I think Aman is right that `npm ci` is probably better than `npm install`: I'd recommend using that instead. Also if you're going to run `npm install`, I don't think you even need to copy `package-lock.json` (which you're explicitly doing because you copy `package*.json` instead of just `package.json`).

Another nit: I'm not a Docker expert so this is my uneducated opinion, but if you're going to run `COPY . .` at the end anyway, I feel like it seems redundant to manually copy `package.json` and `package-lock.json` first? (Also I think it's a little unusual to use `cd` before commands; I think it's more normal to use `WORKDIR`.) I feel like it'd be simpler to do something like this:
```
COPY . .

WORKDIR /app/client
RUN npm install -g @angular/cli
# [...any other client commands to run]

WORKDIR /app/server
RUN npm install
# [...any other server commands to run]

# You're already in /app/server, so you can start the server now and you don't need --prefix:
CMD ["npm", "run", "start:prod"]
```

2023-10-21 16:27 UTC, networkflow commented on server/learnings.txt
> +* Run a NestJS server: `npm run start:dev`
This line should've been changed in assignment 2, not here :)

2023-10-21 16:27 UTC, networkflow commented on server/src/app.module.ts
> +      rootPath: join(__dirname, '..', '../client/dist/client'),
nit: the point of using `path.join` is that it automatically adds in the appropriate folder separators whatever operating system (e.g. it uses `\` for Windows but `/` for Linux). If you're going to use `/` anyway then you don't even need join, which is probably ok, but I wouldn't mix the two (especially since you separated out the first `..` but stuck the second `..` in with the rest of the string).

another nit: this is a very minor detail, but IMO it's slightly confusing how you came up with `../../client/dist/client`. I decided to create a `project_root` constant pointing to the project root directory, and then add `client/dist/client` to that string to get the path to serve:
```
// __dirname is <project_root>/dist/src/, so we back up twice:
 const project_root = join(__dirname, '..', '..');

[...]
     ServeStaticModule.forRoot({
       rootPath: join(project_root, 'client', 'dist', 'client'),
     }),
```

2023-10-22 12:19 UTC, closed without merging

2023-10-22 12:56 UTC, hopeaisulu commented on .dockerignore
> +Thumbs.db
@networkflow  I have 3 .gitignore files, in the root, /server and /client. I should have only one .gitignore file?

2023-10-24 10:01 UTC, hopeaisulu commented
test

2023-10-24 10:01 UTC, hopeaisulu commented
Reopening a PR

2023-10-24 10:02 UTC, hopeaisulu commented on server/src/app.module.ts
> +      rootPath: join(__dirname, '..', '../client/dist/client'),
tst